spec-version:                       0.31.0
name:                               Haskell-Kaleidoscope
version:                            0.1.0.0
# synopsis:
# description:
category:                           Web
homepage:                           https://github.com/Ailrun/Haskell-Kaleidoscope#readme
bug-reports:                        https://github.com/Ailrun/Haskell-Kaleidoscope/issues
author:                             Junyoung Clare Jang
maintainer:                         jjc9310@gmail.com
copyright:                          2021 Junyoung Clare Jang
license:                            MIT
license-file:                       LICENSE
# tested-with:
# build-type:
extra-source-files:
  - README.md
# extra-doc-files:
# data-files:
# data-dir:
github:                             Ailrun/Haskell-Kaleidoscope
# custom-setup:
  # dependencies:

# flags:

# library:
#   ## Common fields
#   source-dirs:
#     - src
#   ghc-options:                      -Wall
#   dependencies:
#     - base
#     - bytestring
#     - containers
#     - llvm-hs
#     - llvm-hs-pure
#     - megaparsec
#     - text
#   ## Library fields
#   # exposed:
#   # exposed-modules:
#   # generated-exposed-modules:
#   # other-modules:
#   # generated-other-modules:
#   # reexported-modules:
#   # signatures:

# internal-libraries:

executables:
  Haskell-Kaleidoscope:
    ## Common fields
    source-dirs:
      - app
      - src
    ghc-options:                    -Wall -threaded -rtsopts -with-rtsopts=-N
    dependencies:
      # - Haskell-Kaleidoscope

      - base
      - bytestring
      - containers
      - llvm-hs
      - llvm-hs-pure
      - megaparsec
      - text
    ## Executable fields
    main:                           Main.hs
    # other-modules:
    # generated-other-modules:

# executable:

# tests:
#   Haskell-Kaleidoscope-test:
#     ## Common fields
#     source-dirs:
#       - test
#     ghc-options:                    -threaded -rtsopts -with-rtsopts=-N
#     dependencies:
#       - Haskell-Kaleidoscope
#     ## Test fields
#     main:                           Spec.hs
#     # other-modules:
#     # generated-other-modules:

# benchmarks:

# defaults:
  # github:
  # ref:
  # path:
  # local:

## Common fields
# buildable:
# source-dirs:
# default-extensions:
# other-extensions:
# ghc-options:
# ghc-prof-options:
# ghcjs-options:
# cpp-options:
# cc-options:
# c-sources:
# cxx-options:
# cxx-sources:
# js-sources:
# extra-lib-dirs:
# extra-libraries:
# include-dirs:
# install-includes:
# frameworks:
# extra-frameworks-dirs:
# ld-options:
# dependencies:
# pkg-config-dependencies:
# build-tools:
# system-build-tools:
# when:
